name: Build OpenJDK 24

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 1 1 */2 *"

jobs:
  build_android:
    strategy:
      matrix:
        arch: ["aarch64"]
        version: [24]
      fail-fast: false

    name: "Build Java ${{ matrix.version }} for Android ${{matrix.arch}}"
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: 24.0.0+19.0.ea
          distribution: temurin

      - name: Install build dependencies
        run: |
          echo ${{ secrets.USERPWD }} | sudo -S apt update
          echo ${{ secrets.USERPWD }} | sudo -S apt -y install autoconf python3 python-is-python3 unzip zip systemtap-sdt-dev libxtst-dev libasound2-dev libelf-dev libfontconfig1-dev libx11-dev libxext-dev libxrandr-dev libxrender-dev libxtst-dev libxt-dev

      - name: Build with CI build script
        run: export TARGET_VERSION=${{ matrix.version }} && echo ${{ secrets.USERPWD }} | sudo -S bash "1_ci_build_arch_${{matrix.arch}}.sh"

      - name: Upload JDK build output
        uses: actions/upload-artifact@v4
        with:
          name: "jdk${{ matrix.version }}-${{matrix.arch}}"
          path: jdk${{ matrix.version }}*.tar.xz

      - name: Upload JRE build output
        uses: actions/upload-artifact@v4
        with:
          name: "jre${{ matrix.version }}-${{matrix.arch}}"
          path: jre${{ matrix.version }}*.tar.xz

      - name: Upload JRE debuginfo build output
        uses: actions/upload-artifact@v4
        with:
          name: "jre${{ matrix.version }}-debuginfo-${{matrix.arch}}"
          path: dizout
